# Generated by Django 3.1.4 on 2020-12-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20201206_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='instructor',
        ),
    ]
