# Generated by Django 3.1.4 on 2020-12-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelTable(
            name='author',
            table='authors',
        ),
    ]
