# Generated by Django 3.1.4 on 2020-12-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20201226_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/%Y-%m-%d/'),
        ),
    ]
