# Generated by Django 3.1.4 on 2021-10-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_news_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='photos/news/%Y-%m-%d/'),
        ),
    ]
