# Generated by Django 3.1.4 on 2021-04-14 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_news_author'),
        ('mainsite', '0005_auto_20210409_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='editor_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editor_choice', to='news.news'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='trending',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trending', to='news.news'),
        ),
    ]
