# Generated by Django 3.1.4 on 2021-04-14 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_menusettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuSettings',
        ),
    ]
